added function to get create food and send it to fe
legosiv/valiant-valkyries pull request #7
Opened 2022-07-27 20:14 UTC by kcaashish

Just added create food function

2022-07-27 21:59 UTC, anirbanmajumder0 commented
Send the food list to the client after initial connection with the client

2022-07-27 22:04 UTC, anirbanmajumder0 requested changes
Send the food list to the client after initial connection with the client. And stop sending the dummy data.

2022-07-28 07:13 UTC, Anirban-Majumder commented on backend/main.py
> +        food_list.append([food_x, food_y, food_direction])
Make this into a separate function cause the client will call the server for new food when old food is eaten.

2022-07-28 07:13 UTC, kcaashish commented on backend/main.py
> +        food_list.append([food_x, food_y, food_direction])
Done

2022-07-28 07:13 UTC, anirbanmajumder0 approved these changes

2022-07-28 07:14 UTC, merged